CREATE TABLE farmers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    fathername VARCHAR(255) NOT NULL,
    mathername VARCHAR(255),
    phone VARCHAR(15) NOT NULL,
    email VARCHAR(255),
    address VARCHAR(255) NOT NULL,
    groupx VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE groupx (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE depo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    depo VARCHAR(255) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(155),
    mobile VARCHAR(11),
    name VARCHAR(200),
    password VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP   
);


CREATE TABLE lands (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account INT,
    description VARCHAR(255) NOT NULL,
    depid INT,
    quantity INT,
    unit VARCHAR(50) NOT NULL,
    showunit VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE units (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Crops (
    id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- invoice sql command
CREATE TABLE invoice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    accountno INT,
    notes VARCHAR(500) NOT NULL,
    description VARCHAR(200),
    crop VARCHAR(200),
    quantity DECIMAL(10, 2),
    price DECIMAL(10, 2),
    name VARCHAR(255) NOT NULL,
    fname VARCHAR(200) NOT NULL,
    invoiceid INT UNIQUE,
    unit VARCHAR(50),
    users VARCHAR(255),
    dpct VARCHAR(255),
    amount DECIMAL(15, 2),
    groupx VARCHAR(100),
    submitdate TIMESTAMP,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
